- name: Install libsodium via Apt
  when: repo_universe_factory_available
  apt: name={{item}} state=latest
  with_items:
  - libsodium13
  - libsodium-dev

- name: Install build dependencies for libsodium
  when: not repo_universe_factory_available
  apt: name={{item}} state=present
  with_items:
  - build-essential
  - autoconf

- include: source.yml
  when: not repo_universe_factory_available
