---
driver                     :
    name                   : <%= if ENV['TRAVIS'] then 'localhost' else 'vagrant' end  %>

provisioner:
    name                   : ansible_push
    verbose                : "vvvv"
    ansible_config         : "test/ansible.cfg"
    idempotency_test       : false
    sudo                   : <%= if ENV['TRAVIS'] then 'True' else 'False' end  %>

platforms:
  - name                   : <%= if ENV['TRAVIS'] then 'travis' else 'ubuntu-14.04' end %>
    provisioner            :
      raw_arguments        : <%= if ENV['TRAVIS'] then '-c local' else '' end %>
    # Should be safely ignored by Travis since connection local
    driver                 :
      box                  : ubuntu/trusty64
    customize              :
      cpus                 : 2
      memory               : 2048

suites:
  - name                   : fastd
    provisioner            :
      playbook             : "test/application/<%= if ENV['TRAVIS'] then 'travis-' else '' end  %>fastd.yml"
      extra_vars           : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

#  - name                   : fastd-enabled
#    provisioner            :
#      playbook             : "test/application/fastd-enabled.yml"
#      extra_vars           : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

#  - name                   : fastd-disabled
#    provisioner            :
#      playbook             : "test/application/fastd-disabled.yml"
#      extra_vars           : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }

#  - name                   : fastd-removed
#    provisioner            :
#      playbook             : "test/application/fastd-removed.yml"
#      extra_vars           : { 'kitchen_connection': 'smart', 'kitchen_hosts': '<%= if ENV['TRAVIS'] then 'localhost' else 'all' end %>' }
