---
dist: trusty
sudo: required
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq git ruby ruby-dev build-essential
  - cd /tmp
  - git clone https://github.com/AutomationWithAnsible/ansible-setup.git

install:
  - /tmp/ansible-setup/example/travis-install
  - cd $TRAVIS_BUILD_DIR/
  - gem install bundler
  - bundle install

script:
  - export TRAVIS=True
# - KITCHEN_YAML=.kitchen.travis.yml bundle exec kitchen test
  - bundle exec kitchen test

after_success:
  - echo "Success"
