---
dist: trusty
sudo: required
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq git python-apt python-pycurl git ruby ruby-dev build-essential autoconf
  - gem install bundler

install:
  - sudo pip install ansible

script:
  - ansible --version
  - export TRAVIS=True
  - bundle install
# - KITCHEN_YAML=.kitchen.travis.yml bundle exec kitchen test
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check tasks/main.yml
  - ansible-playbook -i inventory --connection=local --sudo -vvvv tasks/main.yml
  - bundle exec kitchen test travis

after_success:
  - echo "Success"
