---
dist: trusty
sudo: required
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq git python-apt python-pycurl git ruby ruby-dev build-essential autoconf
  - gem install bundler

install:
  - sudo pip install ansible

script:
  - ansible --version
  - export TRAVIS=True
  - bundle install
# - echo localhost > inventory
  - ansible-playbook -i test/inventory --syntax-check test/application/fastd.yml
  - ansible-playbook -i test/inventory --connection=local --sudo -vvvv test/application/fastd.yml
  - bundle exec kitchen test travis

after_success:
  - echo "Success"
