# status: configured

# tasks file for fastd

- include: installed.yml

- name: Create fastd config directories
  file: path=/etc/fastd/{{item.name}} state=directory recurse=yes
  with_items:
    - "{{fastd_instances}}"

- name: Create fastd configs
  template: src=fastd.conf.j2 dest=/etc/fastd/{{item.name}}/fastd.conf
  with_items: "{{fastd_instances}}"
  notify: Restart fastd

- name: Create fastd secrets
  template: src=secret.conf.j2 dest=/etc/fastd/{{item.name}}/secret.conf
  with_items: "{{fastd_instances_secret}}"
  notify: Restart fastd
  no_log: True

- name: Create fastd peer include directories
  when: item.peer_dir is defined
  file: dest={{item.peer_dir}} state=directory
  with_items: "{{fastd_instances}}"

- name: Create fastd peer configs
  when: item.0.peer_dir is defined
  template: src=peer.config.j2 dest="{{item.0.peer_dir}}/{{item.1.name}}"
  with_subelements:
  - "{{fastd_instances | selectattr('peers', 'defined') | list}}"
  - peers

- name: Add fastd user
  user: createhome=no system=yes shell={{fastd_user_shell}} name={{fastd_user_name}}
