# status: disabled

# Disable startup and stop service
- name: Disable and stop fastd
  service: name=fastd enabled=no state=stopped

- name: Disable and stop rng-tools
  when: fastd_use_rng
  service: name=rng-tools enabled=no state=stopped pattern=/usr/sbin/rngd
