# status: enabled

# tasks file for fastd

- include: configured.yml

- name: rng-tools need to run
  when: fastd_use_rng
  service: name=rng-tools state=started enabled=yes pattern=/usr/sbin/rngd

- name: fastd needs to autostart
  service: name=fastd enabled=yes state=started
