---
# declarative ansible role

#- name: Gather facts
#  setup:

# Remove everything created by this role.
- name: Switching to status removed
  include: removed.yml
  when: status == 'removed'

# Disable this role
- name: Switching to status disabled
  include: disabled.yml
  when: status == 'disabled'

# Enable and deploy this role
- name: Switching to status enabled
  include: enabled.yml
  when: status == 'enabled'
